version: '3'

services:
  ci-frontend:
    build:
      context: .
      dockerfile: DockerfileCiFrontend
    ports:
      - "9000:9000"
  ci-api-mock:
    depends_on:
      - ci-frontend
    build:
      context: .
      dockerfile: DockerfileCiApiMock
    ports:
      - "8080:8080"
  jest-image-snapshot:
    image: navikt/docker-jest-image-snapshot:1.0.0
    depends_on:
      - ci-api-mock
    volumes:
      - ./ci-tests/jest-image-snapshot/tests:/app/tests
      - ./ci-tests/jest-image-snapshot/baseline:/app/baseline
      - ./ci-tests/reports:/app/reports
    environment:
      - HOST=ci-frontend
      - HOST_PORT=9000