version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.0'

executors:
  nais-deployer:
    environment:
      TEAM: teamfamilie
    docker:
      - image: navikt/deployment-cli:latest

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Add github to known hosts
          command: |
            mkdir ~/.ssh
            echo "github.com,140.82.118.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "73:fc:5a:28:30:60:a6:5d:3d:79:ab:e4:54:3f:4e:72"
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Generate version number, github token and docker image tags
          command: |
            export VERSION="$(node -p "require('./package').version")-$CIRCLE_SHA1"
            echo "export VERSION="$(node -p "require('./package').version")-$CIRCLE_SHA1"" >> properties.env
            echo "export DOCKER_TAG=\"$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$VERSION\"" >> properties.env
            cat properties.env >> $BASH_ENV
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/node_modules
      - run:
          name: Bygger test
          command: |
            yarn build:dev
      - run:
          name: Bygger produksjon
          command: |
            yarn build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .
 
  test-unit:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Kjører jest tester
          command: |
            yarn test:unit

  test-ci:
    machine: true
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Kjører ci tester
          command: |
            ./ci-tests/scripts.sh test
      - store_artifacts:
          path: /ci-tests/reports
          destination: reports

  github_tag:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Set up environment variables
          command: |
            cat /home/circleci/project/properties.env >> $BASH_ENV
      - run:
          name: Add github to known hosts
          command: |
            mkdir ~/.ssh
            echo "github.com,140.82.118.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "73:fc:5a:28:30:60:a6:5d:3d:79:ab:e4:54:3f:4e:72"
      - run:
          name: Github tag
          command: |
            git config --global user.email "team.familie@nav.no"
            git config --global user.name "teamfamilie"
            git tag -a $VERSION -m "$VERSION [skip ci]"
            git push --tags

  deploy_docker:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set up environment variables
          command: cat /home/circleci/project/properties.env >> $BASH_ENV
      - run:
          name: Slett test resources
          command: rm -rf development
      - run:
          name: Bygger Docker image
          command: |
            echo $DOCKER_TAG $VERSION
            docker build -t $DOCKER_TAG .
      - run:
          name: Docker push
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin 
            echo "Pushing with tag $DOCKER_TAG"
            docker push $DOCKER_TAG
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - properties.env

  deploy_dev:
      executor: nais-deployer
      steps:
        - attach_workspace:
            at: /home/circleci/project
        - checkout
        - run:
            name: Set up environment variables
            command: cat /home/circleci/project/properties.env >> $BASH_ENV
        - run:
            name: Create github deployment for stable test
            command: |
              deployment-cli deploy create \
              --cluster=dev-sbs \
              --repository=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              --appid=${GITHUB_APP_ID} \
              --key-base64=${GITHUB_PRIVATE_KEY} \
              --team=${TEAM} \
              --version=${VERSION} \
              --resource=./build_n_deploy/naiserator/app-preprod.yaml

  deploy_prod:
      executor: nais-deployer
      steps:
        - attach_workspace:
            at: /home/circleci/project
        - checkout
        - run:
            name: Set up environment variables
            command: cat /home/circleci/project/properties.env >> $BASH_ENV
        - run:
            name: Create github deployment for production
            command: |
              deployment-cli deploy create \
              --cluster=prod-sbs \
              --repository=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              --appid=${GITHUB_APP_ID} \
              --key-base64=${GITHUB_PRIVATE_KEY} \
              --team=${TEAM} \
              --version=${VERSION} \
              --resource=./build_n_deploy/naiserator/app-prod.yaml

workflows:
  version: 2
  build_n_deploy_master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test-unit:
          requires:
            - build
      - test-ci:
          requires:
            - build
      - deploy_docker:
          context: NAIS deployment
          requires:
            - test-unit
            - test-ci
      - deploy_dev:
          context: familie-ci
          requires:
            - deploy_docker
      - slack/approval-notification:
          context: familie-ci
          mentions: 'here'
          message: Godkjenn deploy av branchen \`master\` til \`prod-fss\`
          filters:
            branches:
              ignore: /pull\/.*/
          requires:
            - deploy_dev
      - await-approval-dev:
          context: familie-ci
          type: approval
          filters:
            branches:
              ignore: /pull\/.*/
          requires:
            - deploy_dev
      - github_tag:
          context: familie-ci
          requires:
            - await-approval-dev
      - deploy_prod:
          context: familie-ci
          requires:
            - github_tag
  build_n_deploy_branch:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - test-unit:
          requires:
            - build
      - test-ci:
          requires:
            - build
      - deploy_docker:
          context: NAIS deployment
          requires:
            - test-unit
            - test-ci
      - slack/approval-notification:
          context: familie-ci
          message: Godkjenn deploy av branchen \`${CIRCLE_BRANCH}\` til \`dev-fss\`
          filters:
            branches:
              ignore: /pull\/.*/
          requires:
            - deploy_docker
      - await-approval:
          context: familie-ci
          type: approval
          filters:
            branches:
              ignore: /pull\/.*/
          requires:
            - deploy_docker
      - deploy_dev:
          context: familie-ci
          requires:
            - await-approval