apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknad-kontantstotte
  namespace: default
  labels:
    team: teamfamilie

spec:
  image: navikt/soknad-kontantstotte:{{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isAlive
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  ingresses:
    - "https://soknad-kontantstotte.nav.no"
  vault:
    enabled: true
  resources:
    limits:
      cpu: "3"
      memory: 786Mi
    requests:
      memory: 512Mi
  env:
  - name: NAV_TRUSTSTORE_KEYSTOREALIAS
    value: na
  - name: NAV_TRUSTSTORE_PATH
    value: /var/run/secrets/naisd.io/nav_truststore_path
  - name: APPRES_CMS_URL
    value: https://appres.nav.no
  - name: LOGINSERVICE_URL
    value: https://loginservice.nav.no/login
  - name: APPDYNAMICS_CONTROLLER_HOST_NAME
    value: appdynamics.adeo.no
  - name: APPDYNAMICS_CONTROLLER_PORT
    value: "443"
  - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
    value: "true"
  - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
    value: PROD
  - name: UNLEASH_API_URL
    value: https://unleashproxy.nais.oera.no/api/
  - name: LOADBALANCER_SOKNAD_KONTANTSTOTTE_URL
    value: soknad-kontantstotte.nav.no
  - name: LOADBALANCER_SOKNAD_KONTANTSTOTTE_POOLNAME
    value: na
