apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknad-kontantstotte
  namespace: deafult
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 9000
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  ingresses:
    - "https://soknad-kontantstotte-q.nav.no"
    - "https://soknad-kontantstotte.nais.oera-q.local"
    - "https://soknad-kontantstotte-dev-sbs.dev.nav.no"
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  env:
    - name: BASE_PATH
      value: {{base_path}}
